-- Customer Success AI Agent - Database Schema
-- 4-table design: customers, conversations, messages, tickets
-- Safe to run multiple times (all CREATE/ALTER statements are idempotent)

-- ── customers ─────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS customers (
    id          SERIAL       PRIMARY KEY,
    customer_id VARCHAR(255) UNIQUE NOT NULL,
    created_at  TIMESTAMP    DEFAULT NOW()
);

-- ── conversations ─────────────────────────────────────────────────────────────
-- Groups individual messages into logical sessions per channel.
-- A new conversation is started when a customer messages after being idle
-- for more than SESSION_TIMEOUT_MINUTES (handled in application code).
CREATE TABLE IF NOT EXISTS conversations (
    id             SERIAL       PRIMARY KEY,
    session_id     VARCHAR(255) UNIQUE NOT NULL,  -- UUID generated by app
    customer_id    VARCHAR(255) NOT NULL REFERENCES customers(customer_id) ON DELETE CASCADE,
    channel        VARCHAR(50)  NOT NULL,          -- 'email' | 'whatsapp' | 'web'
    started_at     TIMESTAMP    DEFAULT NOW(),
    last_active_at TIMESTAMP    DEFAULT NOW(),
    message_count  INT          DEFAULT 0
);

-- ── messages ──────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS messages (
    id          SERIAL       PRIMARY KEY,
    customer_id VARCHAR(255) NOT NULL REFERENCES customers(customer_id) ON DELETE CASCADE,
    session_id  VARCHAR(255) REFERENCES conversations(session_id) ON DELETE SET NULL,
    channel     VARCHAR(50)  NOT NULL,   -- 'email' | 'whatsapp' | 'web'
    message     TEXT         NOT NULL,   -- inbound customer text
    response    TEXT         NOT NULL,   -- outbound agent text
    source      VARCHAR(50)  NOT NULL,   -- 'docs' | 'escalation' | 'ai' | 'acknowledgment' | 'fallback'
    created_at  TIMESTAMP    DEFAULT NOW()
);

-- ── tickets ───────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS tickets (
    id          SERIAL       PRIMARY KEY,
    customer_id VARCHAR(255) NOT NULL REFERENCES customers(customer_id) ON DELETE CASCADE,
    status      VARCHAR(20)  NOT NULL DEFAULT 'open',  -- 'open' | 'escalated' | 'closed'
    priority    VARCHAR(10)  NOT NULL DEFAULT 'low',   -- 'low' | 'medium' | 'high'
    reason      VARCHAR(50)  NOT NULL DEFAULT '',      -- 'pricing' | 'refund' | 'legal' | 'angry' | ''
    created_at  TIMESTAMP    DEFAULT NOW()
);

-- ── Migrations (idempotent — safe to run on an existing database) ─────────────
DO $$ BEGIN
    -- tickets.priority (added in v2)
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_name = 'tickets' AND column_name = 'priority'
    ) THEN
        ALTER TABLE tickets ADD COLUMN priority VARCHAR(10) NOT NULL DEFAULT 'low';
    END IF;

    -- tickets.reason (added in v2)
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_name = 'tickets' AND column_name = 'reason'
    ) THEN
        ALTER TABLE tickets ADD COLUMN reason VARCHAR(50) NOT NULL DEFAULT '';
    END IF;

    -- messages.session_id (added in v3 — nullable for backward compatibility)
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_name = 'messages' AND column_name = 'session_id'
    ) THEN
        ALTER TABLE messages
            ADD COLUMN session_id VARCHAR(255)
            REFERENCES conversations(session_id) ON DELETE SET NULL;
    END IF;
END $$;

-- ── Indexes ───────────────────────────────────────────────────────────────────
CREATE INDEX IF NOT EXISTS idx_conversations_customer_id ON conversations(customer_id);
CREATE INDEX IF NOT EXISTS idx_conversations_last_active ON conversations(last_active_at);
CREATE INDEX IF NOT EXISTS idx_messages_customer_id      ON messages(customer_id);
CREATE INDEX IF NOT EXISTS idx_messages_session_id       ON messages(session_id);
CREATE INDEX IF NOT EXISTS idx_tickets_customer_id       ON tickets(customer_id);
CREATE INDEX IF NOT EXISTS idx_tickets_status            ON tickets(status);
